<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="回归测试组"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="1.114">
  <properties />
            <testcase name="loginAndLogout" time="1.114" classname="com.yoyotesting.startwithonebrowser.LoginAndLogoutTestNG">
                <failure type="java.lang.AssertionError"
                  message="expected [泛微移动办公云OA(eteams)：一体化的团队协作移动办公云平台1] but found [泛微移动办公云OA(eteams)：一体化的团队协作移动办公云平台]"
              >
<![CDATA[java.lang.AssertionError: expected [泛微移动办公云OA(eteams)：一体化的团队协作移动办公云平台1] but found [泛微移动办公云OA(eteams)：一体化的团队协作移动办公云平台]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:453)
  org.testng.Assert.assertEquals(Assert.java:463)
  com.yoyotesting.startwithonebrowser.LoginAndLogoutTestNG.loginAndLogout(LoginAndLogoutTestNG.java:28)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.runSuites(TestNG.java:1028)
  org.testng.TestNG.run(TestNG.java:996)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
  org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
